### ISSUE TITLE
[BUG] Status check not triggering

### ISSUE THREAD

**Issue by andrejohansson** [cocogitto/cocogitto-bot#6]
**Describe the bug**
I might be missing something, but what is required for the status to be reported?

![image](https://user-images.githubusercontent.com/2828428/156851193-c8c52c95-7185-4130-8898-e434bc02d2dd.png)

**To Reproduce**

1. Install bot in settings ui: https://github.com/apps/cocogitto-bot
1. add cocogitto check to workflow: https://docs.cocogitto.io/ci_cd/#conventional-commits-check
1. protect branch and set status required: 
![image](https://user-images.githubusercontent.com/2828428/156851368-5725d0fe-75dc-4959-8d9b-0ad472b36a91.png)

**Expected behavior**
Expected status to be reported to the PR. But it just waits indefinitely.

**Comment by oknozor** [comment]
Hello @andrejohansson,, I am not able to reproduce : 
![image](https://user-images.githubusercontent.com/24563836/156873977-eff7901b-77b0-4dfe-8d75-47b9756c2b70.png)

Maybe you just did a PR during a deployment and your status check was not reported. 
Does this still happen if you push a new commit to your pull request ? 
If so I will need a more info : the repository address, is it public?

**Comment by andrejohansson** [comment]
I tried pushing a new commit today, and the bot comments the PR almost immediately:

![image](https://user-images.githubusercontent.com/2828428/156890150-730e6cc3-aa53-4613-b339-4c611f3f6c5b.png)

but still the "checks" section says it´s waiting for info.

Could it be something with that the action is building on multiple targets (mac, win, linux) but only executes cocogitto on ubuntu?

My build file looks like this:

```yaml
name: "test-on-pr"
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    # cancel all runs on the same branch except the latest
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        all_but_latest: true
        access_token: ${{ github.token }}

    # checkout with depth 0 for cocogitto
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    # check that commits follow conventional commit standard
    - name: Conventional commits check (ubuntu-only)
      if: matrix.platform == 'ubuntu-latest'
      uses: oknozor/cocogitto-action@v2

    # install prerequisites
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

... and so on
```

When ubuntu-latest runs I can confirm that cocogitto is executed:

![image](https://user-images.githubusercontent.com/2828428/156890365-f74c341e-b535-428b-ba7b-820f88f2bf90.png)

But nowhere i see something about any status being reported.
